title: Rebecca Chappelear
email: rebecca.chappelear@gmail.com
description: >
  This will be the meta description indexed by Google
baseurl: ""
url: "http://localhost:4000"
collections:
  projects:
    output: true
defaults:
  - scope:
      path: "images"
    values:
      image: true
